#!/bin/bash

check_even () {
    local mod=2
    echo "The value of mod is $mod inside of fuction"
    if [ $(("$1" % $mod)) -eq 0 ]
    then 
       echo "The number $1 is even!";
    else 
       echo "The number $1 is odd!"
    fi
}


number=666

check_even $number
echo "The value of $mod is outside of function"